# Generated by Django 4.2.4 on 2023-08-15 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_suscribe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suscribe',
            new_name='Subscribe',
        ),
    ]
