# Generated by Django 4.2.4 on 2023-08-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_suscribe_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
