# Generated by Django 4.2.4 on 2023-08-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_comments_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
